hmcts/acr-base-importer

- base-image-import.yml
[AB#244]
```
[ ] Yes
[x] No
```
> Fix build schedule

- base-image-import.yml
- base-image-scan.sh
[AB#244]
```
[ ] Yes
[x] No
```
> Neuvector scan

- base-image-import.yml
- base-image-scan.sh
[AB#244]
```
[ ] Yes
[x] No
```
> Add exit condition. Add temp logging

- base-image-import.yml
- base-image-scan.sh
- import-gcr-image.sh
[AB#244]
```
[ ] Yes
[x] No
```
> Agent pool + fixes

- base-image-scan.sh
[AB#244]
```
[ ] Yes
[x] No
```
> Fix 'or' typo

- base-image-import.yml
[AB#94]
```
[ ] Yes
[x] No
```
> Use prod subscription

- base-image-import.yml
[[AB#597](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/597)]
```
[ ] Yes
[x] No
```
> Update neuvector rest api hostname

- base-image-import.yml
[[AB#597](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/597)]
```
[ ] Yes
[x] No
```
> Update keyvault. Add start/finish notifications

- base-image-import.yml
[[AB#597](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/597)]
```
[ ] Yes
[x] No
```
> Fix vault service connection

- base-image-import.yml
- base-image-scan.sh
- slack-notify.sh
[[AB#597](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/597)]
```
[ ] Yes
[x] No
```
> Notify failure + success

- base-image-import.yml
> Reduce parallelism to increase reliability (hopefully).

- base-image-import.yml
https://tools.hmcts.net/jira/browse/DTSPO-5978
Added Node 16 Alpine.
```
[ ] Yes
[X] No
```
> Added Node 16 Alpine

- base-image-import.yml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> remove api from endpoint

- base-image-import.yml
> Add node 18

- base-image-import.yml
https://tools.hmcts.net/jira/browse/DTSPO-10310
Disable scan to get new base images in
> Disable scan

- base-image-import.yml
> Re-enable image scan

- base-image-import.yml
Reverts hmcts/acr-base-importer#41
> Revert "Re-enable image scan"

- acr-repositories.yaml
Length must be > 5
```
[ ] Yes
[ ] No
```
> Fix rule name lengths

- base-image-import.yml
Reverts hmcts/acr-base-importer#54 in favour of updating permissions for newer service connection
> Revert "Update back to serviceconnection for other jobs besides cache"

- acr-repositories.yaml
DTSPO-14808
Split neuvector scanner and updater
```
[ ] Yes
[ x ] No
```
> split scanner and updater

- acr-cache.sh
- acr-repositories.yaml
> Dtspo 14808

- acr-repositories.yaml
Add Oathtool and JQ to image caching to prevent pull limiting
> DFPL: Add JQ and Oathtool to caching

- acr-repositories.yaml
> Make ruleName over 4 characters long!

- README.md
- acr-cache.sh
- acr-repositories.yaml
N/A
JQ lives in the GitHub container registry, ACR supports other registries and our script now does too :)
> feat: support other registries

- acr-repositories.yaml
> Add alpine

- README.md
- acr-repositories.yaml
> Adding redis image

- README.md
- acr-repositories.yaml
> Add testcontainers/sshd

- README.md
- acr-repositories.yaml
https://tools.hmcts.net/jira/browse/FACT-1881
> FACT-1881 adding azurite image

- acr-repositories.yaml
https://tools.hmcts.net/jira/browse/FACT-1881
added missing line for registry so it knows where to grab image from
> FACT-1881_2 added registry line for azurite

- README.md
- acr-repositories.yaml
https://tools.hmcts.net/jira/browse/FACT-1881
adding new image atmoz/sftp
> FACT-1881 added new atmoz sftp image for send letter service

- acr-repositories.yaml
I see us using old curl in a bunch of places from when a random version was imported... lets allow keeping more up to date
> Import curl

- README.md
N/A
Corrected name of acr-repositories.yaml file in Supported Upstream Image Repositories section of README.md.  This fixes the link to the file.
Confirmed that link now displays acr-repositories.yaml file
- [no] Does this PR introduce a breaking change
> Corrected filename in README.md
